syntax = "proto3";

package drone;

// In this RPC the C++ client sends GimbalFeedback and the Node.js server streams back GimbalSpeed.
service DroneComm {
  rpc Communicate (stream GimbalFeedback) returns (stream GimbalSpeed);
}

message GimbalFeedback {
  double pitch_feedback = 1;
  double roll_feedback = 2;
  double yaw_feedback = 3;
}

// Using optional so that only the fields that need updating are sent.
message GimbalSpeed {
  optional double pitch = 1;
  optional double roll = 2;
  optional double yaw = 3;
}
